services:
  - type: web
    name: flaskblog
    env: python
    buildCommand: ""
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-secret-key-here
